language: cpp

script: make test

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      name: "Macos xcode 10.1"
    - os: linux
      dist: bionic
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      name: "Linux gcc 7"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      name: "Linux gcc 8"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      name: "Linux gcc 9"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
      name: "Linux gcc 10"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
      name: "Linux clang 8"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-9
          packages:
            - clang-9
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
      name: "Linux clang 9"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
      name: "Linux clang 10"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-11
          packages:
            - clang-11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11"
      name: "Linux clang 11"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-12
          packages:
            - clang-12
      env:
        - MATRIX_EVAL="CC=clang-12 && CXX=clang++-12"
      name: "Linux clang 12"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-13
          packages:
            - clang-13
      env:
        - MATRIX_EVAL="CC=clang-13 && CXX=clang++-13"
      name: "Linux clang 13"
        
before_install:
    - eval "${MATRIX_EVAL}"
